package pe.upeu.biblioandes.presentation.theme

import androidx.compose.ui.graphics.Color

// Paleta propia de BiblioAndes: terracota/cuero (libros) + verde azulado y
// rosa polvo como acentos textiles andinos. Distinta del morado por defecto.

val BALibroPrimaryLight = Color(0xFF8D5B24)
val BALibroOnPrimaryLight = Color(0xFFFFFFFF)
val BALibroPrimaryContainerLight = Color(0xFFFFDCBE)
val BALibroOnPrimaryContainerLight = Color(0xFF2E1500)
val BALibroSecondaryLight = Color(0xFF3D6659)
val BALibroOnSecondaryLight = Color(0xFFFFFFFF)
val BALibroSecondaryContainerLight = Color(0xFFBFECDB)
val BALibroOnSecondaryContainerLight = Color(0xFF002016)
val BALibroTertiaryLight = Color(0xFF8E4A5C)
val BALibroOnTertiaryLight = Color(0xFFFFFFFF)
val BALibroTertiaryContainerLight = Color(0xFFFFD9E0)
val BALibroOnTertiaryContainerLight = Color(0xFF3B0716)
val BALibroErrorLight = Color(0xFFBA1A1A)
val BALibroOnErrorLight = Color(0xFFFFFFFF)
val BALibroErrorContainerLight = Color(0xFFFFDAD6)
val BALibroOnErrorContainerLight = Color(0xFF410002)
val BALibroBackgroundLight = Color(0xFFFFF8F4)
val BALibroOnBackgroundLight = Color(0xFF221A11)
val BALibroSurfaceLight = Color(0xFFFFF8F4)
val BALibroOnSurfaceLight = Color(0xFF221A11)
val BALibroSurfaceVariantLight = Color(0xFFF0E0D0)
val BALibroOnSurfaceVariantLight = Color(0xFF504539)
val BALibroOutlineLight = Color(0xFF837469)
val BALibroOutlineVariantLight = Color(0xFFD5C4B4)
val BALibroScrimLight = Color(0xFF000000)
val BALibroInverseSurfaceLight = Color(0xFF382F26)
val BALibroInverseOnSurfaceLight = Color(0xFFFEEEE0)
val BALibroInversePrimaryLight = Color(0xFFFFB870)
val BALibroSurfaceDimLight = Color(0xFFE7D8CB)
val BALibroSurfaceBrightLight = Color(0xFFFFF8F4)
val BALibroSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val BALibroSurfaceContainerLowLight = Color(0xFFFFF1E5)
val BALibroSurfaceContainerLight = Color(0xFFFBEADC)
val BALibroSurfaceContainerHighLight = Color(0xFFF5E4D6)
val BALibroSurfaceContainerHighestLight = Color(0xFFEFDFD1)

val BALibroPrimaryDark = Color(0xFFFFB870)
val BALibroOnPrimaryDark = Color(0xFF4B2900)
val BALibroPrimaryContainerDark = Color(0xFF6B3E00)
val BALibroOnPrimaryContainerDark = Color(0xFFFFDCBE)
val BALibroSecondaryDark = Color(0xFFA3D0C1)
val BALibroOnSecondaryDark = Color(0xFF0A372C)
val BALibroSecondaryContainerDark = Color(0xFF244E42)
val BALibroOnSecondaryContainerDark = Color(0xFFBFECDB)
val BALibroTertiaryDark = Color(0xFFFFB1C4)
val BALibroOnTertiaryDark = Color(0xFF561D2C)
val BALibroTertiaryContainerDark = Color(0xFF6F3341)
val BALibroOnTertiaryContainerDark = Color(0xFFFFD9E0)
val BALibroErrorDark = Color(0xFFFFB4AB)
val BALibroOnErrorDark = Color(0xFF690005)
val BALibroErrorContainerDark = Color(0xFF93000A)
val BALibroOnErrorContainerDark = Color(0xFFFFDAD6)
val BALibroBackgroundDark = Color(0xFF191210)
val BALibroOnBackgroundDark = Color(0xFFEFDFD1)
val BALibroSurfaceDark = Color(0xFF191210)
val BALibroOnSurfaceDark = Color(0xFFEFDFD1)
val BALibroSurfaceVariantDark = Color(0xFF504539)
val BALibroOnSurfaceVariantDark = Color(0xFFD5C4B4)
val BALibroOutlineDark = Color(0xFF9C8E80)
val BALibroOutlineVariantDark = Color(0xFF504539)
val BALibroScrimDark = Color(0xFF000000)
val BALibroInverseSurfaceDark = Color(0xFFEFDFD1)
val BALibroInverseOnSurfaceDark = Color(0xFF382F26)
val BALibroInversePrimaryDark = Color(0xFF8D5B24)
val BALibroSurfaceDimDark = Color(0xFF191210)
val BALibroSurfaceBrightDark = Color(0xFF413830)
val BALibroSurfaceContainerLowestDark = Color(0xFF130D0B)
val BALibroSurfaceContainerLowDark = Color(0xFF221A15)
val BALibroSurfaceContainerDark = Color(0xFF261E19)
val BALibroSurfaceContainerHighDark = Color(0xFF312823)
val BALibroSurfaceContainerHighestDark = Color(0xFF3D332D)
